### ISSUE TITLE
Smooth scrolling on anchor links + don't hide behind fixed header

### ISSUE THREAD

**Issue by simonw** [natbat/rockybeaches#14]

**Comment by simonw** [comment]
https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

```css
a.anchor {
    display: block;
    position: relative;
    top: -250px;
    visibility: hidden;
}
```

**Comment by simonw** [comment]
https://gomakethings.com/smooth-scrolling-links-with-only-css/
```css
html {
	scroll-behavior: smooth;
}

@media screen and (prefers-reduced-motion: reduce) {
	html {
		scroll-behavior: auto;
	}
}
```
